from phBot import *
import QtBind

pVersion = '0.0.1'
pName = 'UltimateINFO'
pUrl = 'https://raw.githubusercontent.com/GAUCHE0/Plugins/main/UltimateINFO.py'

#GUI YAPILANDIRMASI
gui = QtBind.init(__name__,pName)
lblInfo = QtBind.createLabel(gui,"ULTIMATE PLUGINLERI HAKKINDA ACIKLAMALAR:",21,11)
lblInfo2 = QtBind.createLabel(gui," - SPECIAL THANKS TO |JellyBitz| ABOUT PYTHON DEVELOPMENT..",400,11)
btnUltimateController = QtBind.createButton(gui,'btnUltimateController_clicked',"  UltimateController  ",600,30)
btnUltimateChat = QtBind.createButton(gui,'btnUltimateChat_clicked',"      UltimateChat      ",600,55)
btnUltimateLocker = QtBind.createButton(gui,'btnUltimateLocker_clicked',"     UltimateLockeR    ",600,80)
btnUltimatePacketTool = QtBind.createButton(gui,'btnUltimatePacketTool_clicked',"  UltimatePacketTooL ",600,105)
btnUltimateUpdater = QtBind.createButton(gui,'btnUltimateUpdater_clicked',"    UltimateUpdater   ",600,130)
btnUltimateTombala = QtBind.createButton(gui,'btnUltimateTombala_clicked',"    UltimateTombala   ",600,155)
btnUltimateArena = QtBind.createButton(gui,'btnUltimateArena_clicked',"     UltimateArena    ",600,180)
btnIletisim = QtBind.createButton(gui,'btnIletisim_clicked',"   GAUCHE ILETISIM   ",600,250)
lstInfo = QtBind.createList(gui,21,30,570,250)
#BUTON ISLEVLERI	
def btnUltimateController_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimateController:\n   # BU PLUGIN LIDER LISTESINE EKLENMIS CHARLARIN CHAT EKRANINDAN DIGER CHARLARA CESITLI\nISLEMLER YAPTIRIR.\n# GENEL DESTEK KOMUTLARI:\n - START : BOTU BASLAT.\n - STOP : BOTU DURDUR.\n - TRACE #OYUNCU : LIDERE YADA YAZDIGIN CHARA TRACE AT.\n - NOTRACE : TRACE DURDUR.\n - ZERK : ZERK HAZIRSA KULLAN.\n - RETURN : RETURN SCROLL KULLAN.\n - TP #A #B : A-B ARASI TELEPORT.\n - CHAT #CESIT #MESAJ : MESAJ GONDER\n - SETAREA #PosX? #PosY? #Range? #PosZ? :KASMA ALANI.\n - SETRADIUS #Radius? : RANGE DEGISTIR.\n - CAPE #RENK? : PVP MODU.\n - INJECT #Opcode #Encrypted? #Data? : PAKET ENJEKTE ET.')
	QtBind.append(gui,lstInfo,'# FORTRESS DESTEK KOMUTLARI:\n - HXY : HOTAN FORTRESS TELEPORT KODU.\n - JXY : JANGAN FORTRESS TELEPORT KODU.\n    # X : BULUNDUGUN GATE NUMARASI.\n    # Y : GIDECEGIN GATE NUMARASI.\n# SCROLL KOMUTLARI:\n - DRUG : DRUG SCROLL KULLANIMI.(ENVANTER 1.SAYFA 27.SLOT)\n - RES : RES SCROLL KULLANIMI.(ENVANTER 1.SAYFA 28.SLOT)\n - DAMAGEINC : DAMAGE INCREASE SCROLL KULLANIMI.(ENVANTER 1.SAYFA 29.SLOT)\n - DAMAGEABS : DAMAGE ABSORPTION SCROLL KULLANIMI.(ENVANTER 1.SAYFA 30.SLOT)\n - HP : HP SCROLL KULLANIMI.(ENVANTER 1.SAYFA 31.SLOT)\n - MP : MP SCROLL KULLANIMI.(ENVANTER 1.SAYFA 32.SLOT) \n    # NOT: SCROLL KULLANIMI ICIN ENVANTERDE GEREKLI SLOTLARA KONULMALIDIR..\n # EGLENCE KOMUTLARI:\n - SIT : OTUR - KALK.\n - COME : MEYDAN OKUMA EFEKTI.')
	QtBind.append(gui,lstInfo,'- MERHABA : SELAMLAMA EFEKTI.\n# TARGET MODU DESTEK KOMUTLARI: \n - TARGET ON : TARGET MODUNU AKTIF ET.\n - TARGET OFF : TARGET MODUNU DEAKTIF ET.\n - DEFF ON : DEFANS MODU AKTIF ET.\n - DEFF OFF : DEFANS MODU DEAKTIF ET.')
def btnUltimateChat_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimateChat:\n   # BU PLUGIN ILE 10 SANIYEDE BIR SPAM MESAJ ATILABILIR, SECILEN KOSULA GORE ISTEDIGINIZ CHAT\nEKRANINA MESAJ GONDEREBILIRSINIZ.\n   # BUNA EK OLARAK SCRIPTE EKLEYECEGINIZ BASIT BIR KODLA SCRIPT ESNASINDA OTO MESAJ\nATTIRABILIRSINIZ..\n   # ORNEK: "chat,all,SELAM" VEYA "chat,private,GAUCHE,SELAM"')
def btnUltimateLocker_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimateLockeR:\n    # BU PLUGIN AKADEMI VE PARTI LISTELERINDEN OTOMATIK GIRIS YAPARKEN ISTENMEYEN KISILERIN \nGIRMESINI ENGELLEMEK ICIN TASARLANMISTIR.\n    # BIR NEVI SIFRELEME SISTEMI OLUP, MASTER CHARIN BELIRLENEN SORUYU SORMASININ ARDINDAN \nGIRIS YAPAN CHARIN DOGRU CEVABI VERMESIYLE CALISIR.\n    # KURULUM :\n - PARTI MASTER: PARTY MASTERI OLACAK CHARIN ADI.\n - AKADEMI MASTER: AKADEMI MASTERI OLACAK CHARIN ADI.\n - SORU: CHAT EKRANINDA SORDURMAK ISTEDIGIN SORU.\n - CEVAP: SORULAN SORUYA VERILMESINI ISTEDIGIN YANIT.\n(SIFRE NITELIGINDE OLUP BASKA BIR KISI ILE PAYLASMAYIN.)')
def btnUltimatePacketTool_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimatePacketTooL:\n    # BU PLUGIN CLIENTTEN SERVERA GONDERILEN OPCODE PAKETLERINI VEYA SERVERDAN CLIENTE\nGELEN OPCODE PAKETLERINI GOSTERMEKTEDIR.\n    # EK OLARAK CLIENTTEN SERVERA OPCODE ENEJEKTE EDEBILIR VE CEVRENIZDEKI NPCLERIN\nDATALARINA ULASABILIRSINIZ.')
def btnUltimateUpdater_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimateUpdater:\n    # BU PLUGIN BILGSAYARINIZDA GITHUB.COM UZERINDEN YAYINLANAN HERHANGI BIR YAZILIMCININ\nPLUGININI BULDUGU TAKTIRDE GUNCELLER..\n KULLANIMI:\n"GUNCELLEMELERI KONTROL ET" BUTONUNA BASTIKTAN SONRA;\n LISTEDE "GUNCELLEME BULUNDU" YAZAN PLUGINLERIN UZERINE TIKLAYIP,\n"SECILEN PLUGINI GUNCELLE" BUTONUNA BASINIZ.\n    # ISLEM BITIMINDE BOTUNUZU YENIDEN BASLATIRSANIZ VEYA "PLUGIN" SEKMESINDE "YENIDEN\nYUKLE" BUTONUNA TIKLARSANIZ PLUGININ SON VERSIYONUNU KULLANMAYA BASLAYABILIRSINIZ..')
def btnUltimateTombala_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimateTombala:\n    # BU PLUGIN ILE MEVCUT MANAGER UZERINDEN GIRILEN BUTUN CHARLAR OTOMATIK TOMBALAYA\nKAYIT YAPARLAR.')
def btnUltimateArena_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'UltimateArena:\n    # BU PLUGIN ILE MEVCUT MANAGER UZERINDEN GIRILEN BUTUN CHARLAR OTOMATIK ARENAYA\nKAYIT YAPARLAR.\n\n - RANDOM ARENA\n - PT ARENA\n - JOB ARENA\n - GUILD ARENA')
def btnIletisim_clicked():
	QtBind.clear(gui,lstInfo)
	QtBind.append(gui,lstInfo,'- ILETISIM:\n   # DISCORD: "GAUCHE#8710"\n   # E-MAIL: "can.berk.cetin@hotmail.com.tr"\n\n- SOSYAL MEDYA:\n    # INSTAGRAM: "can.berk.cetin"\n    # YOUTUBE: "JoySro Hazar GAUCHE" ')

log('Plugin: '+pName+' '+pVersion+' BASARIYLA YUKLENDI')
